/* Shared navigation only. Question banks and study records remain in each app. */
window.STUDY_CATALOG = [
  {id:'sao',group:'agencies',short:'สตง.',title:'สำนักงานการตรวจเงินแผ่นดิน',role:'นักวิเคราะห์นโยบายและแผน',icon:'สตง.',color:'sao',sprint:'sao-sprint.html',sprintKey:'sao48:v1',sprintTopics:9,description:'อ่านตามขอบเขต 9 หัวข้อ ฝึกโจทย์แยกหมวด และทวนตัวบท',search:'sao ตรวจเงิน',actions:['read','practice','sources']},
  {id:'opsmoac',group:'agencies',short:'สป.เกษตร',title:'สำนักงานปลัดกระทรวงเกษตรและสหกรณ์',role:'นักวิเคราะห์นโยบายและแผน',icon:'กษ.',color:'opsmoac',priority:true,sprint:'opsmoac-sprint.html',sprintKey:'opsmoac60:v1',sprintTopics:5,sprintCount:100,description:'จำลองสอบ 100 ข้อเน้นตรงขอบเขต แผนเกษตร ภารกิจ สป. และงานนักวิเคราะห์ฯ',search:'opsmoac สป.กษ.',actions:['read','practice','sources']},
  {id:'rd',group:'agencies',short:'สรรพากร',title:'กรมสรรพากร',role:'นักวิชาการพัสดุ',icon:'ภษ.',color:'rd',description:'จัดซื้อจัดจ้าง การเงิน งบประมาณ และความรู้เกี่ยวกับกรม',search:'rd ภาษี พัสดุ',actions:['read','practice','sources']},
  {id:'energy',group:'agencies',short:'สป.พลังงาน',title:'สำนักงานปลัดกระทรวงพลังงาน',role:'นักวิชาการพลังงาน',icon:'พน.',color:'energy',description:'แผนพลังงาน น้ำมัน ก๊าซ ไฟฟ้า พลังงานทดแทน และกฎหมาย',search:'energy',actions:['read','practice','sources']},
  {id:'law-sources',group:'resources',short:'ตัวบทฉบับเต็ม',title:'ตัวบทฉบับเต็มและเอกสารอ้างอิง',role:'รวมลิงก์แยกตามหน่วยงาน',icon:'file',color:'law-sources',description:'ค้นชื่อกฎหมายหรือเอกสาร แล้วกดเปิดต้นฉบับจากแหล่งเผยแพร่',search:'พรบ พ.ร.บ. PDF กฎหมาย ลิงก์',actions:[]},
  {id:'laws',group:'resources',short:'กฎหมายกลาง',title:'กฎหมายกลางที่ใช้สอบร่วมกัน',role:'สรุปและแบบฝึกหัด',icon:'book',color:'laws',description:'ทบทวนพื้นฐานกฎหมายและระเบียบที่ใช้ได้หลายหน่วยงาน',search:'พรบ พ.ร.บ. ระเบียบ',actions:['read','exam','sources']},
  {id:'compare',group:'resources',short:'เทียบขอบเขตสอบ',title:'เปรียบเทียบขอบเขตและวางแผนอ่าน',role:'ภาพรวมวิชาที่ใช้ร่วมกัน',icon:'layers',color:'compare',description:'ดูแกนร่วมและส่วนต่างของหน่วยงาน เพื่อจัดลำดับการอ่าน',search:'ตาราง แผน',actions:[]},
  {id:'english-course',group:'english',short:'คอร์สภาษาอังกฤษ',title:'ภาษาอังกฤษแบบเป็นคอร์ส',role:'เรียนทีละบทและฝึกต่อเนื่อง',icon:'Aa',color:'english-course',description:'เลือกหมวด เรียนเนื้อหา แล้วฝึกแบบทดสอบประจำบท',search:'english course',actions:[]},
  {id:'english',group:'english',short:'อังกฤษพื้นฐาน',title:'ภาษาอังกฤษพื้นฐาน',role:'บทเรียนสั้นพร้อมแบบฝึกหัด',icon:'Hi',color:'english',description:'ทวนคำศัพท์ ประโยค และการออกเสียงในบทเรียนที่ต้องการ',search:'english',actions:[]},
  {id:'diprom',group:'archive',short:'กรมส่งเสริมอุตสาหกรรม',title:'กรมส่งเสริมอุตสาหกรรม',role:'คลังเนื้อหาที่สอบไปแล้ว',icon:'กสอ.',color:'diprom',description:'กลับมาอ่านเนื้อหาและฝึกโจทย์ในคลังเดิมได้ทุกเมื่อ',search:'diprom อุตสาหกรรม',actions:['read','practice','sources']},
  {id:'namban',group:'archive',short:'กรมทรัพยากรน้ำบาดาล',title:'กรมทรัพยากรน้ำบาดาล',role:'คลังเนื้อหาที่สอบไปแล้ว',icon:'นบ.',color:'namban',description:'เก็บบทอ่าน แบบทดสอบ และเอกสารเดิมไว้ให้กลับมาทบทวน',search:'namban น้ำบาดาล',actions:['read','exam','sources']}
].sort((a,b)=>Number(!!b.priority)-Number(!!a.priority)).map(item => ({...item,file:item.id+'.html'}));
