(function(){'use strict';
 const D=window.OPS_WRITING,$=id=>document.getElementById(id),key='opsmoac-writing:v1';
 const E=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 if(!D||D.questions?.length!==8||D.groups?.map(g=>g.cards.length).join(',')!=='5,6,6'){$('loadNotice').hidden=false;return;}
 const ids=new Set(D.questions.map(q=>q.id)),cards=D.groups.flatMap(g=>g.cards.map((c,i)=>({...c,id:g.id+'-'+i,group:g.title,number:i+1}))),cardIds=new Set(cards.map(c=>c.id));
 let state={selected:D.questions[0].id,drafts:{},checks:{},known:[],card:0},storageOK=true;
 try{const s=JSON.parse(localStorage.getItem(key)||'null');if(s&&typeof s==='object'){if(ids.has(s.selected))state.selected=s.selected;for(const id of ids){if(typeof s.drafts?.[id]==='string')state.drafts[id]=s.drafts[id].slice(0,30000);if(Array.isArray(s.checks?.[id]))state.checks[id]=[...new Set(s.checks[id].filter(n=>Number.isInteger(n)&&n>=0&&n<D.questions.find(q=>q.id===id).check.length))];}if(Array.isArray(s.known))state.known=[...new Set(s.known.filter(id=>cardIds.has(id)))];if(Number.isInteger(s.card)&&s.card>=0&&s.card<cards.length)state.card=s.card;}}catch(_){storageOK=false;$('storageNotice').hidden=false;}
 function save(){try{localStorage.setItem(key,JSON.stringify(state));storageOK=true;}catch(_){storageOK=false;$('storageNotice').hidden=false;}return storageOK;}
 function links(keys){return keys.map(k=>{const s=D.sources[k];return `<a href="${E(s.url)}" target="_blank" rel="noopener noreferrer">${E(s.title)} ↗</a>`;}).join('');}
 $('memoryGroups').innerHTML=D.groups.map((g,gi)=>`<details class="memory-group" ${gi===0?'open':''}><summary>${E(g.title)}</summary><p class="mnemonic">${E(g.mnemonic)}</p><p>${E(g.story)}</p><p class="muted">${E(g.note)}</p><button type="button" data-toggle="${g.id}">สลับเปิด / ปิดคำอธิบาย</button><div class="memory-grid">${g.cards.map((c,i)=>`<details class="memory-item" ${gi===0?'open':''}><summary>${i+1}. ${E(c.cue)}</summary><h4>${E(c.title)}</h4><p>${E(c.detail)}</p><p class="muted">ภาพจำที่แต่ง: ${E(c.example)}</p><a href="${E(D.sources[c.source].url)}" target="_blank" rel="noopener noreferrer">อ่านต้นฉบับ ↗</a></details>`).join('')}</div></details>`).join('');
 $('memoryGroups').addEventListener('click',e=>{const b=e.target.closest('[data-toggle]');if(!b)return;const items=[...b.closest('.memory-group').querySelectorAll('.memory-item')],open=!items.every(x=>x.open);items.forEach(x=>x.open=open);});
 function recall(){const c=cards[state.card];$('recallProgress').textContent=`บัตร ${state.card+1}/${cards.length} · คุณระบุว่าจำได้ ${state.known.length}/${cards.length}`;$('recallGroup').textContent=c.group;$('recallQuestion').textContent=`ข้อ ${c.number} มีชื่อเต็มว่าอะไร?`;$('recallCue').textContent=c.cue;$('recallHint').open=false;$('recallAnswer').hidden=true;$('recallAnswer').innerHTML=`<b>${E(c.title)}</b><p>${E(c.detail)}</p>${links([c.source])}`;$('revealRecall').hidden=false;$('known').disabled=true;$('again').disabled=true;}
 $('revealRecall').addEventListener('click',()=>{$('recallAnswer').hidden=false;$('revealRecall').hidden=true;$('known').disabled=false;$('again').disabled=false;});
 function rate(known){const c=cards[state.card];state.known=state.known.filter(id=>id!==c.id);if(known)state.known.push(c.id);state.card=(state.card+1)%cards.length;save();recall();$('recallQuestion').focus({preventScroll:true});}
 $('known').addEventListener('click',()=>rate(true));$('again').addEventListener('click',()=>rate(false));
 function updateChecks(){const q=D.questions.find(q=>q.id===state.selected);$('checkProgress').textContent=`คุณตรวจว่ามีแล้ว ${(state.checks[q.id]||[]).length}/${q.check.length} จุด`;}
 function renderQuestion(focus=false){const q=D.questions.find(q=>q.id===state.selected),i=D.questions.indexOf(q);$('questionNav').innerHTML=D.questions.map((x,n)=>`<button type="button" data-question="${x.id}" aria-pressed="${x.id===q.id}">${n+1}. ${E(x.title)}${n===0||n===2?' · เริ่มก่อน':''}</button>`).join('');$('writingLabel').textContent=`แนวที่ ${i+1} · ลองฝึกประมาณ ${q.minutes} นาที`;$('writingTitle').textContent=q.title;$('writingPrompt').textContent=q.prompt;$('writingMemory').textContent='จำ: '+q.memory;$('writingOutline').innerHTML=q.outline.map(s=>`<li>${E(s)}</li>`).join('');$('draft').value=state.drafts[q.id]||'';$('modelAnswer').open=false;$('writingModel').innerHTML=q.model.map(p=>`<p>${E(p)}</p>`).join('');$('writingAvoid').textContent=q.avoid;$('writingChecklist').innerHTML=q.check.map((s,n)=>`<label class="check-row"><input type="checkbox" data-check="${n}" ${(state.checks[q.id]||[]).includes(n)?'checked':''}><span>${E(s)}</span></label>`).join('');$('writingSources').innerHTML=links(q.sources);$('saveStatus').textContent=storageOK?'บันทึกเฉพาะเบราว์เซอร์นี้ ไม่ส่งคำตอบไปที่ใดและไม่ซิงก์ข้ามเครื่อง':'ขณะนี้บันทึกไม่ได้ ควรคัดลอกคำตอบเก็บเอง';updateChecks();if(focus)$('writingTitle').focus();}
 $('questionNav').addEventListener('click',e=>{const b=e.target.closest('[data-question]');if(!b)return;state.selected=b.dataset.question;save();renderQuestion(true);});
 $('draft').addEventListener('input',()=>{state.drafts[state.selected]=$('draft').value;$('saveStatus').textContent=save()?'บันทึกคำตอบในเบราว์เซอร์นี้แล้ว':'บันทึกไม่ได้ ควรคัดลอกคำตอบเก็บเองก่อนปิดหน้า';});
 $('writingChecklist').addEventListener('change',e=>{const input=e.target.closest('[data-check]');if(!input)return;const n=Number(input.dataset.check),selected=state.checks[state.selected]||[];state.checks[state.selected]=selected.filter(x=>x!==n);if(input.checked)state.checks[state.selected].push(n);save();updateChecks();});
 $('sourceList').innerHTML=links(Object.keys(D.sources));recall();renderQuestion();
})();
