/* Optional integration check: requires jsdom. Run node tests/opsmoac-sprint.dom.js.
   This checks DOM behavior, not browser rendering or mobile layout. */
const {JSDOM,VirtualConsole}=require('jsdom'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..'),key='opsmoac60:v1',html=fs.readFileSync(path.join(root,'opsmoac-sprint.html'),'utf8'),scripts=['opsmoac-sprint-data.js','opsmoac-sprint-core.js','opsmoac-sprint.js'].map(f=>fs.readFileSync(path.join(root,f),'utf8'));
const errors=[];
function load(saved={},blocked=false){const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(html,{url:'https://exam.test/opsmoac-sprint.html',runScripts:'outside-only',virtualConsole:vc}),w=dom.window;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.confirm=()=>false;if(blocked)Object.defineProperty(w,'localStorage',{get(){throw Error('blocked')}});else for(const [k,v]of Object.entries(saved))w.localStorage.setItem(k,v);for(const s of scripts)w.eval(s);return w;}
let w=load({'sao48:v1':'{"sentinel":true}','exam-tutor-v1:opsmoac':'{"sentinel":true}'});
const el=s=>w.document.querySelector(s),click=s=>{const e=el(s);assert.ok(e,s);e.click();},state=()=>JSON.parse(w.localStorage.getItem(key)),shown=s=>!el(s).hidden;
function answer(correct=true){const s=state().session,q=w.OPS_SPRINT.questions.find(q=>q.id===s.ids[s.idx]);click(`[data-option="${correct?q.a:(q.a+1)%4}"]`);}
function finish(){let guard=0;while(shown('#quiz')){assert.ok(guard++<65);const s=state().session;if(s.answers[s.ids[s.idx]]===undefined)answer();click('#next');}}
assert.equal(w.document.querySelectorAll('#sets article').length,3);click('[data-start="1"]');assert.ok(el('#next').disabled);answer(false);assert.ok(el('#answerFeedback .feedback'));assert.ok(el('#answerFeedback a'));click('#mark');click('#next');const saved=JSON.stringify(state().session);click('#pause');click('[data-start="2"]');assert.equal(JSON.stringify(state().session),saved);
const storage=Object.fromEntries(Object.keys(w.localStorage).map(k=>[k,w.localStorage.getItem(k)]));w.close();w=load(storage);click('#resume');assert.equal(JSON.stringify(state().session),saved);finish();assert.match(el('.result-score').textContent,/19\/20/);assert.equal(state().history.length,1);click('#resultWrong');finish();assert.match(el('.result-score').textContent,/1\/1/);click('#backDashboard');assert.ok(el('#wrongBtn').disabled);click('#markedBtn');finish();click('#backDashboard');
for(const set of ['2','3']){el('input[value="exam"]').checked=true;click(`[data-start="${set}"]`);answer();assert.equal(el('#answerFeedback .feedback'),null);finish();assert.match(el('.result-score').textContent,/20\/20/);click('#backDashboard');}
click('#allBtn');answer();assert.equal(el('#answerFeedback .feedback'),null);finish();assert.match(el('.result-score').textContent,/60\/60/);assert.equal(w.document.querySelectorAll('#result details').length,60);assert.equal(w.document.querySelectorAll('#result tbody tr').length,5);assert.equal(w.localStorage.getItem('sao48:v1'),'{"sentinel":true}');assert.equal(w.localStorage.getItem('exam-tutor-v1:opsmoac'),'{"sentinel":true}');w.close();
w=load({[key]:'{broken'});assert.ok(shown('#storageNotice'));assert.equal(w.document.querySelectorAll('#sets article').length,3);w.close();w=load({},true);assert.ok(shown('#storageNotice'));click('[data-start="1"]');click('[data-option]');assert.ok(!el('#next').disabled);w.close();assert.deepEqual(errors,[]);console.log('PASS DOM integration: all 3 sets and 60-question exam, explanations/sources, resume, cancelled restart, marks, wrong retry, score/history, separate storage, malformed and blocked storage. Layout not tested by JSDOM.');
